title: Elizabeth Teng
description: 
theme: minima
email: eteng@protonmail.com
social: 
  linkedin: elizabeth-teng

navigation:
  - title: "Home"
    url: "/"
  - title: "Astronomy Research"
    url: "/astronomy.md
  - title: "Resume"
    url: "/et_resume.pdf"   # Link to your resume here
