title: Elizabeth Teng
description: 
theme: minima
email: eteng@protonmail.com
social: 
  linkedin: elizabeth-teng


header_pages:
  - about.md    # Example page
  - et_resume.pdf  # Link to the resume
  - astronomy.md

navigation:
  - title: "Home"
    url: "/"
  - title: "About me"
    url: "/about.md"
  - title: "Astronomy Research"
    url: "/astronomy.md
  - title: "Resume"
    url: "/et_resume.pdf"   # Link to your resume here
